# Generated by Django 3.2.16 on 2022-12-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=100)),
                ('content_body', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('writers', models.CharField(default='author', max_length=50)),
                ('content_category', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
